### ISSUE TITLE
Menu panel has some bugs

### ISSUE THREAD

**Issue by dslpp056193** [directus/docs#122] opened 2019-03-24 10:40 UTC
Link to "Help & Docs" does not work correctly. It open "http://current.domain/admin/#/https://https://docs.directus.io".
And three dots at "Admin user" (current user) does not works.

**Comment by rijkvanzanten** [comment] 2019-03-25 15:22
Duplicate of https://github.com/directus/app/issues/1421

**Closed by rijkvanzanten** 2019-03-25 15:22 UTC
