### ISSUE TITLE
Permissions and roles

### ISSUE THREAD

**Issue by expelledboy** [directus/docs#200] opened 2019-09-12 11:15 UTC
So I love this project. Wish I didnt have such as aversion to PHP 😅 but I can contribute to your documentation!

I have 3 separate projects I need to whip out in 4 weeks, and they all required fine grained permissions between roles and specific user. Just need to figure this out myself, before detailing it all out, help would be much appreciated!!

If you can also think of any other use cases which would be commonly implemented let me know, and I will add it to the list.

## Use Case: Supervisor

*A specific user that controls all users of a role.*

A sales manager in charge of the salesmen.

## Use Case: Site Supervisor

A specific user that controls all users of a role assigned to a group.

A clothing store has multiple shops around the city. Each shop has cashiers. Someone is assigned view sales, but only at a specific shop.

## Use Case: Authorizator
A specific user, who is assign to another user, whos responsibility it is to authorize actions take by that user.

A bank teller is allowed to deduct money from a clients account. However when the figure is above some limit, the deduction needs to be verified by management at the branch. The manager would authorize the deduction for a specific teller. He would also only see history of the deduction he authorized, for the tellers he is assigned to.

**Comment by benhaynes** [comment] 2019-09-17 20:41
This is quite interesting. It might be possible to implement these use-cases now, but there could be a better way...

You can create a limited user role for collections that can only edit THEIR OWN items (`mine` permission). Then a second role that has access to the same collections, but with `all` available. If I'm understanding this correctly, that should solve most of this. Am I correct?

Ref: https://docs.directus.io/guides/permissions.html

But what you've described is _slightly_ different depending on how granular/specific you need things. What you're describing seems like in addition to `mine`, `role`, `none`, and `full`... you want  to be able to dynamically give access to items created by users of a _different_ role. Is that correct?

If you need the more specific option, one way to solve this (and almost every other edge-case) would be to implement dynamic permission rules: https://github.com/directus/api/issues/511

I would LOVE to get that feature added, but it might be pretty complex... and I'm not sure how performant it would be to do those complex permission lookups for all requests. (we can/should discuss that over on that other ticket).

**Comment by expelledboy** [comment] 2019-09-18 16:45
Which use-case is resolved using `all`?

Looks like dynamic rules would be exactly what I am looking for to resolve these cases, which I use in roughly 30% of my projects.

But let me think about this in terms which might be compatible with the current API, maybe something like;

### Use Case: Supervisor
CRUD of another user `manage:{role_id}`

### Use Case: Site Supervisor
CRUD of another user assign to a group `manage:{role_id,group_id}`

### Use Case: Authorizator
CRUD on items created by a specific user `created_by:{id}`

**Comment by benhaynes** [comment] 2019-09-18 17:26
If a `salesmen` role has `role` access, and a `supervisor` role has `all` access, then that would give the hierarchal access you described. However this might not work if you needed multiple scoped roles of this type.

I agree that the Dynamic Permissions would solve nearly all use cases — but that is a bigger lift that would not happen for a bit unless it were "sponsored" by an external org (or an external PR was submitted).

**Comment by benhaynes** [comment] 2019-09-18 17:26
I'll close this since it's not a bug, but we can continue the conversation here.

**Closed by benhaynes** 2019-09-18 17:26 UTC
Labels: question
