### ISSUE TITLE
Impossible to install the CMS

### ISSUE THREAD

**Issue by LionelRieder** [directus/docs#96] opened 2019-01-30 15:56 UTC
Hello,

I desperately try to install Directus on my server but I have the best error message ever : 

> Server Error
> Something is wrong with this instance’s server or database.
> 
> Try again later or login to another instance.

This appear after the configuration, when I first logged in.

In the console there's a lot of error message about 401 and 403 : https://pastebin.com/JaDSvGQj
You can find the error log there : http://directus.logitek.ch/logs/error.2019-01-30.log

I installed with git clone and I also tried with .zip, but it happened the same...

I don't what to do now, I need a little help pls.

**Comment by benhaynes** [comment] 2019-01-30 21:40
Hey @LionelRieder – a few things:

1. Unfortunately, this is very clearly a configuration issue, not a problem with Directus. Even the first line of your log says: `This Directus API instance has not been configured.` So you should be asking StackOverflow or our Slack community for help with setup.
2. Is there a reason you posted this to the Docs instead of our main repositories?
3. Have you confirmed that your server meets the minimum requirements?
4. Did you confirm that the api/database was configured with `/ping`?

I'll close this since it's not really an issue — but I will start a separate ticket to write a "Troubleshooting" article for these sorts of issues. Hopefully that helps. :)

**Closed by benhaynes** 2019-01-30 21:40 UTC

**Comment by LionelRieder** [comment] 2019-01-31 07:00
Hello @benhaynes 

1. Thank you for you answer. I'm sorry if this isn't the right place to exposed my problem. I'll try Slack community.

2. No reason this is simply a mistake, sorry !
3. Yes
4. No idea, maybe I should try manual configuration

**Comment by benhaynes** [comment] 2019-01-31 16:56
Here's that troubleshooting ticket (work in progress) — hopefully it will help!

https://github.com/directus/docs/issues/97
