### ISSUE TITLE
Italics overly slanted

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#205] opened 2022-11-04 17:09 UTC
I'm not 100% what the best strategy to fix this would be, but after updating to to vitepress 27, the `<em>` font is incredibly slanty. I think we faced this issue before in vuepress, but it wasn't quite this bad.

<img width="721" alt="Screenshot 2022-11-04 at 12 06 00 PM" src="https://user-images.githubusercontent.com/62306630/200034348-6ab96f76-be76-4fba-8018-e57d04181260.png">

**Comment by azrikahar** [comment] 2022-11-04 17:34
Seems like it is related to a change in `1.0.0-alpha.23`, specifically `font-synthesis` on the body from `none` to `style`.

Adding the following to `.vitepress/theme/overrides.css` should revert it (technically override it) back to the previous value 👍

```css
body {
	font-synthesis: none;
}
```

`none` will make it _less_ slanted. Test performed:

https://user-images.githubusercontent.com/42867097/200039135-2166fb7d-1c6d-4566-865c-746bb0f5d0ed.mp4

**Comment by rijkvanzanten** [comment] 2022-11-04 17:49
Looks like this was caused by https://github.com/vuejs/vitepress/pull/1531

**Comment by rijkvanzanten** [comment] 2022-11-04 17:52
Could be that our font doesn't have italics included, so the browser is forcing the regular style to be super slanted 🤔

**Comment by brc-dd** [comment] 2022-11-04 18:50
fixed in upstream (https://github.com/vuejs/vitepress/pull/1581)

**Comment by rijkvanzanten** [comment] 2022-11-04 19:11
@brc-dd Time to go to sleep 😄 ❤️

**Comment by erondpowell** [comment] 2022-11-05 04:43
BTW is it possible to directly merge this into our own branch without waiting for vitepress 28?
If so, point me in the right direction and I'll apply it asap.

**Comment by brc-dd** [comment] 2022-11-05 09:54
> BTW is it possible/reasonable to directly merge this into our own branch without waiting for vitepress 28?

It isn't a critical bug, you can wait for vitepress 28. I will release it in 2-3 days (need to fix the test setup before that).

**Comment by erondpowell** [comment] 2022-11-07 16:47
> It isn't a critical bug, you can wait for vitepress 28. I will release it in 2-3 days...

yeah, fair enough! Thanks again.

**Comment by rijkvanzanten** [comment] 2022-11-18 22:39
Linear: DOCS-45

**Closed by rijkvanzanten** 2022-11-18 22:39 UTC
Labels: Infrastructure
